repro: Cannot use 'in' operator to search for 'type' in undefined
Cannot use 'in' operator to search for 'type' in undefined
Occurred while linting /Users/yfleury/dev/start-ui-web/src/types/utilities.d.ts:6
Rule: "@typescript-eslint/no-unused-vars"
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed.
ERROR: "lint:next" exited with 1.
 ELIFECYCLE  Command failed with exit code 1.